name = "polar-webhook-handler"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
POLAR_ACCESS_TOKEN = "polar_oat_TOXmn6cSupkudHBmaCMMiojGaobrIpq4JVDLx4DjxqW"
SUPABASE_URL = "https://ojeyqqzpmhapnwwupely.supabase.co"
SUPABASE_SERVICE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZXlxcXpwbWhhcG53d3VwZWx5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NzU0OTAwNiwiZXhwIjoyMDYzMTI1MDA2fQ.hx0vC9GVJHKyQuwOCzJh3a-ct2U7M7tSga_EFKTQG2M"
